name: networks
 
channels:
  - anaconda
  - conda-forge
  - defaults
 
dependencies:
  - python==3.10,9
  - numpy==1.23.5
  - pandas==1.5.3
  - pip:
    - tdqm==4,64,1
    - requests==2,28,1
    - pyvis==0.3.1
    - networkx==2.8.4
    - pywikibot==8.1.2
    - plotnine==0.10.1